name: Update README with Recent Activity

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://github.com/mhmithun.atom"
          readme_path: "./README.md"
          max_post_count: 5
          comment_tag_name: "activity"
          commit_message: "chore: update readme with recent activity"
